
services:    
  jib:
    build: .
    container_name: jib
    restart: always
    volumes:
      - .:/go/src/
    environment:
      MYSQL_DNS: root:root@tcp(jib-mysql:3306)/jib?timeout=5s
    ports:
      - "8000:8000"
      - "2121:2121"

  jib-mysql:
    image: mysql
    container_name: jib-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.mysql:/var/lib/mysql
      - ./scripts/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
 
