
services:    
  vessel-dev:
    build: .
    container_name: vessel-dev
    restart: always
    volumes:
      - .:/go/src/
    environment:
      MYSQL_DNS: root:root@tcp(vessel-mysql:3306)/assets?timeout=5s
    ports:
      - "8080:8080"

  vessel-mysql:
    image: mysql
    container_name: vessel-mysql
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.mysql:/var/lib/mysql
      - ./scripts/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
 
